# Generated by Django 5.0 on 2023-12-27 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_useraction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAction',
        ),
    ]
